- go.mod
- go.sum
- k8s/gvclient.go
- k8s/translation.go
- k8s/translation_test.go
Translate patch requests in translation layer, as metadata fields that are custom, non-kubernetes common, or are in extraFields need to have their paths updated if the provided path is based on the resource's metadata object. If the provided path uses the kubernetes path, the translation layer will not change it.
This came up while working on admission control, but I think it warrants a separate PR before that upcoming one, which is still in-progress.
Resolves https://github.com/grafana/grafana-app-sdk/issues/14
> [bugfix] Translate patch operations for kubernetes

- resource/schema.go
Fix the value for `ClusterScope` schema scope to be `Cluster` instead of `Clustered`.
Currently the values for cluster-level scope are different between kindsys and app sdk, which means that generating cluster-scoped CRDs is impossible – https://github.com/grafana/kindsys/blob/main/kindcat_custom.cue#L165.
Sine the kindsys value is `Cluster` and that's also the official term in Kubernetes, this is the suggested way to fix the problem
> Use correct string value for cluster-level CRD scope

- resource/simplestore.go
- resource/simplestore_test.go
In resource.SimpleStore.Update, make a Get call first to get the current metadata (as only the spec is passed), then run the ObjectMetadataOptions on the resulting metadata. Otherwise, the subsequent PUT call in the underlying Client erases the existing non-managed metadata (such as finalizers).
> [SimpleStore] Ensure Update call doesn't erase existing metadata

- docs/tutorials/issue-tracker/02-defining-our-kinds.md
The group field is required. User can miss this if hand-coding the example.
> Group is a required field

- codegen/templates/operator/main.tmpl
golangci-lint has version 1.53.3 complained about the missing error value check.
> Add an error check to keep the linter happy

- operator/informer_controller.go
- operator/informer_controller_test.go
- operator/opinionatedwatcher.go
- operator/util.go
Currently, in `operator.InformerController`, a user can set a `RetryPolicy` func that will dictate when a failed watcher event should be retried. However, any subsequent actions taken on that object will dequeue any outstanding retries. This is ideal in the default case, where a new update supersedes the old one, but has conflicts with the `OpinionatedWatcher`, as updates which bump the ResourceVersion, but not the Generation, are never received by the underlying update code (`OpinionatedWatcher` drops them and reports back a success). That means if an update fails and enters the retry queue, but a subsequent update which changes non-spec content is received, the outstanding retry for the original update, _which still needs to be performed_, is dropped, and the update code behind the …
> [operator] Improved Retry Queue logic in InformerController

- cmd/grafana-app-sdk/templates/Makefile.tmpl
Check for the existance of plugin.json or Magefile.go before attempting to build the plugin. Fixes #37
> Don't attempt to build the plugin if files are missing

- operator/informer_controller.go
- operator/informer_controller_test.go
Fix bug in the OpinionatedRetryDequeuePolicy where it would dequeue on the same generation instead of on different generations, added tests for the policy to ensure it behaves correctly.
> [bugfix] OpinionatedRetryDequeuePolicy incorrect equality check

- .github/workflows/pr.yml
Use the same version of golangci-lint in the GH actions as we do in the Makefile.
> [Actions] Fix Linter Version

- k8s/translation.go
Thema in generated code was unhappy with the unmarshal call missing a few fields in the metadata. Made sure those fields are present. This is a short-term fix, with a better, full fix that should be done to make sure the complete metadata object is passed to the Unmarshal call, rather than being fragmented between Unmarshal and SetCommonMetadata.
> [bugfix] Translate RawToObject fix for newer Thema versions

- codegen/templates/operator/telemetry.tmpl
Update codegen for otel resource init so it doesn't try to merge with default and have problems every time the schema version gets updated.
Unblocks https://github.com/grafana/grafana-app-sdk/pull/81 and https://github.com/grafana/grafana-app-sdk/pull/82
> [codegen/operator] Update OpenTelemetry init in the operator codegen

- .github/workflows/main.yml
- .github/workflows/release.yml
Update main/release GH workflows to use go 1.21.
> Update main/release GH workflows to use go 1.21.

- k8s/translation.go
- k8s/translation_test.go
Don't marshal the updateTimestamp into annotations if it's a zero time, allowing it to unmarshal into the creationTimestamp on later unmarshal if unset.
> Don't marshal the updateTimestamp into annotations if it's a zero time

- resource/simplestore.go
- resource/store.go
- resource/typedstore.go
Have resource-package Stores Update() methods update CommonMetadata.UpdateTimestamp in the object they're updating. This is a semi-temporary measure to prevent needing admission control to update the UpdateTimestamp, but also keep the kubernetes client from taking on what should be business logic.
> [resource] Stores Update() methods update CommonMetadata.UpdateTimestamp

- .github/workflows/release.yml
Go release action is currently failing due to using go 1.20 instead of 1.21.
> Update the go version used in the release action.

- cmd/grafana-app-sdk/templates/local/generated/operator.yaml
- codegen/templates/operator/config.tmpl
This PR makes a few small fixes for codegen when handling admission webhooks:
- `ValidatingWebhookConfiguration` generation is now checking whether validating (not mutating) webhook is enabled
- If webhooks are enabled codegen now provides env vars for the port and paths to TLS cert / key
- Operator config now parses webhook configuration (for now without checking if webhooks are enabled but if env vars are empty it doesn't fail)
To make it easier to write & test webhooks locally.
> Fix codegen for admission webhooks

- .github/dependabot.yml
Add a separate dependabot group for CUE dependencies alongside with the current catch-all group.
CUE version are known to break compatibility between updates and we don't want to block other dependencies from being updated.
> Add a separate dependabot group for CUE dependencies

- codegen/jennies/gotypes.go
- codegen/testing/golden_generated/customkind2/customkind2_gen.go.txt
- codegen/thema/jennies/wrappedtype.go
Use sanitized exported kind name as go type for models, instead of using exported machine name. This is consistent with the previous thema codegen for model types.
> [codegen] Consistent Generated Model Naming

- plugin/router/router.go
To be used when creating an OpenAPI spec programatically 
As we're working with subrouters, we need to keep track of the current subpath 
By exposing it, we don't have to duplicate that information
> Expose subrouter's current path

- resource/store.go
- resource/store_test.go
- resource/typedstore.go
Update Store / TypedStore methods to skip namespace checks for cluster-scoped resources.
Cluster-scoped resources are not meant to have namespaces.
> Skip namespace checks in stores for cluster-scoped resources

- examples/operator/basic/basic.go
- examples/operator/opinionated/opinionated.go
- examples/resource/store/store.go
- k8s/admission.go
- k8s/admission_test.go
- k8s/client.go
- k8s/client_registry.go
- k8s/client_test.go
- k8s/gvclient.go
- k8s/manager.go
- k8s/negotiator.go
- k8s/schemaless.go
- k8s/schemaless_test.go
- k8s/translation.go
- k8s/translation_test.go
- k8s/webhooks.go
- k8s/webhooks_test.go
- k8s/wrappers.go
- operator/informer_controller.go
- operator/informer_controller_test.go
- operator/informer_kubernetes.go
- operator/opinionatedwatcher.go
- operator/opinionatedwatcher_test.go
- operator/reconciler.go
- operator/reconciler_test.go
- operator/simplewatcher_test.go
- plugin/router/resourcegroup_router.go
- plugin/router/resourcegroup_router_test.go
- simple/operator.go
Implement the changes to the `resource` package in all other packages. This PR does _not_ include updates to codegen, this will be a subsequent PR.
A final PR will be made after codegen changes with any fixes that come up in more extensive local kubernetes testing.
> Implement New resource.Kind and resource.Object in Other Packages

- cmd/grafana-app-sdk/templates/Makefile.tmpl
The scripts correctly declare that they expect bash (by using `#!/usr/bin/env bash`), but the generated makefile is calling these scripts as `sh local/scripts/...`, which basically discards the shebang and assumes that `sh` is `bash`.
Remove `sh` from the Makefile to fix this.
> Fix calls to local scripts

- cmd/grafana-app-sdk/util.go
When using `grafana-app-sdk project init` files are being created with the executable bit set in cases where it's not needed (e.g. some code, makefiles, etc). Given how there are two different functions, `writeFile` and `writeExecutableFile`, it's clear that this was not the intention.
Modify `writeFile` so that it creates files with the read/write bits set, but not the executuable one.
Modify both `writeFile` and `writeExecutableFile` so that the process' umask is respected (i.e. pass 0666 instead of 0644).
> Fix generated files' permissions

- codegen/templates/operator/watcher.tmpl
- codegen/templates/plugin/handler_resource.tmpl
- codegen/templates/plugin/main.tmpl
- codegen/templates/resourceobject.tmpl
- codegen/templates/schema.tmpl
- codegen/testing/golden_generated/customkind/customkind_object_gen.go.txt
- codegen/testing/golden_generated/customkind/customkind_schema_gen.go.txt
- codegen/testing/golden_generated/customkind/customkind_thema_codec_gen.go.txt
- codegen/thema/jennies/codec.go
Update generated resource.Object-implementation code to use the Kind as the type name, rather than Object. This is a breaking change we're rolling into this branch's release as it will be required for the apiserver work.
> [kind-object-refactor] Codegen Object using Kind Name

- docs/README.md
- docs/migrations/README.md
- docs/migrations/v0.15.md
Add new docs section for migrations, include migration notes for 0.14x -> 0.15.x
> [docs] Add Migration Notes Section

- docs/operators.md
- operator/reconciler.go
This PR updates `docs/operators.md` file, adding new changes related to how to build operators using `grafana-app-sdk`.
So our documentation for operators is aligned with the current SDK status
> Updating Operator docs

- cmd/grafana-app-sdk/project_local.go
When configured with `webhooks.converting: true` in `local/config.yaml`, the generated CRD(s) were not being updated with the webhook conversion strategy in the `dev-bundle.yaml` file, only in-memory. This PR writes the in-memory change back to the YAML before it is written out to `dev-bundle.yaml`.
> [bugfix] Local CRD Generation with Webhook Conversion Strategy

- Makefile
Add  target to install the binary built with all flags from local, just to simplify the process from running:
```shell
make build && cp target/grafana-app-sdk $GOPATH/bin/grafana-app-sdk
```
into
```shell
make install
```
Will error if `GOPATH` is not set.
> Add `make install` target

- codegen/templates/templates.go
- codegen/testing/golden_generated/customkind/customkind_object_gen.go.txt
- codegen/testing/golden_generated/customkind/customkind_thema_codec_gen.go.txt
codegen: Fix flipped arguments in time.Time getters, resulting in a bug where `GetUpdateTimestamp()` always returned a zero time in generated `resource.Object` implementations (this also caused `GetCommonMetadata().UpdateTimestamp` to be a zero time as well as that function used `GetUpdateTimestamp()` to fetch the update timestamp).
> [bugfix][codegen] Fix flipped arguments in time.Time getters.

- docs/README.md
- docs/resource-objects.md
Update docs/resource-objects.md based on the changes from v0.15, and update the docs/README to fix some dead links and note temporary nature of the plugin package.
Resolves https://github.com/grafana/grafana-app-sdk/issues/253
> [docs] Update Resource Objects doc with v0.15+ changes

- docs/code-generation.md
- docs/custom-kinds/writing-kinds.md
Update code-generation doc and moved some kind codegen info into writing kinds doc for consistency.
Resolves https://github.com/grafana/grafana-app-sdk/issues/252
> [docs] Update code-generation doc

- cmd/grafana-app-sdk/project.go
- cmd/grafana-app-sdk/templates/operator_Dockerfile.tmpl
- go.mod
This reverts https://github.com/grafana/grafana-app-sdk/pull/197 and upgrades the SDK and generated content to 1.22.
After #248 was merged, the replace directive is obsolete an in fact prevents the build from succeeding.
> Remove now-unnecessary replace directive from project codegen

- .github/dependabot.yml
It looks like dependabot isn't processing submodules correctly (as `grafana-plugin-sdk-go` is now several versions behind), added a second entry to dependabot's config explicitly for the `plugin` module to see if that resolves it.
> Add a second entry in dependabot for the plugin submodule.

- resource/kind.go
- resource/kind_test.go
Add convenience methods for getting a `schema.GroupVersionResource` and `schema.GroupVersionKind` in `resource.Kind`, to avoid the need to assemble these two types each time a user needs them when interacting with kubernetes code.
> Add convenience methods for GVR and GVK in resource.Kind.

- cmd/grafana-app-sdk/templates/plugin.json.tmpl
Updated the reference to the plugin.json schema (it was pointing to the old one).
> Plugin.json: update schema reference URL

- cmd/grafana-app-sdk/generate.go
- codegen/cuekind/generators.go
- codegen/cuekind/generators_test.go
Go model type generator's GoTypes jenny was missing the boolean in its configuration telling it how to group kinds, which defaults to `false` (group by `group`). Updated the generator to take an argument to set this, like the Resource type generator, and supply the value from the CLI flag `--kindgrouping`, the same as with resource types.
> Respect the `--kindgrouping` flag in models go code generation

- cmd/grafana-app-sdk/generate.go
Don't shadow the crdFiles variable, as that was causing the generated CRD files to never get added to the full list of files to write to disk.
> [CLI/bugfix] Fix CRD File Generation from CLI

- codegen/templates/plugin/handler_resource.tmpl
This commit fixes codegen for backend plugin router by ensuring that router service interface uses consistent interface method signatures.
To make sure that the codegen works again and produces valid Go code.
> Fix backend plugin codegen

- cmd/grafana-app-sdk/templates/local/Tiltfile
`find_overlapping` was assuming that all overlapping resources would have a namespace, this PR changes the Tiltfile to use a `namespace` function that returns the namespace if present, or an empty string if not (for non-namespaced resources).
> Tiltfile: don't error on find_overlapping for cluster-scoped resources.

- operator/opinionatedwatcher.go
- operator/opinionatedwatcher_test.go
- operator/reconciler.go
- operator/reconciler_test.go
- simple/operator.go
Have NewOpinionatedWatcher and NewOpinionatedReconciler error on a finalizer which exceed the kubernetes finalizer max length. Allow a user to customize the finalizer generation function of simple.Operator.
> Have NewOpinionatedWatcher and NewOpinionatedReconciler error when finalizer exceeds max length

- operator/kubeconfig.go
We noticed there's no common, standardised way to load a kubeconfig from an operator using the SDK, this PR adds a function that makes developers able to load that from a given path.
So that developers have a standardised way to load their operator kubeconfigs.
> feat: add operator kubeconfig loader

- README.md
Remove caveat about `go install` being broken from the README as `go install` works now as of version `v0.17.8` (https://github.com/grafana/grafana-app-sdk/issues/189).
> Update README to remove note about broken go install.

- k8s/gvclient.go
Properly set started when k8s.WatchResponse translation layer starts, fixing bug found by @ferruvich
> [k8s] Properly set started when k8s.WatchResponse translation layer starts.

- k8s/gvclient.go
- k8s/gvclient_test.go
Have the k8s package properly parse the kubernetes' errors.StatusError type if returned and return a `*k8s.ServerResponseError` wrapping it. Add tests for error parsing. Resolves https://github.com/grafana/grafana-app-sdk/issues/301
> [k8s] Properly parse the kubernetes' errors.StatusError type

- operator/informer_customcache.go
- operator/informer_customcache_test.go
- operator/informer_processor.go
`CustomCacheInformer` uses an `operator.informerProcessor` to distribute events to all listeners (ResourceWatchers added by users). When the reflector submits a list/watch event, it goes through the On<X> method in the Informer, then hits `informerProcessor.distribute`, which writes the event to every listener to process in its own queue. `informerProcessor.distribute` calls `informerProcessorListener.push` on each listener, which pushes the event to a channel which should be constantly being pulled from by `informerProcessorListener.pop`, which is started by `informerProcessorListener.run` (which distributes the events popped off the channel by pop to the ResourceWatcher for the listener), which, for each listener is started by `informerProcessor.run`. However, if `distribute` gets …
> [CustomCacheInformer] Fix startup race condition between controller and processor

- .github/workflows/pr.yml
Per [depndabot docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#common-dependabot-automations), dependabot-specific steps can be run with the check `github.actor == 'dependabot[bot]'`. Use `github.actor != 'dependabot[bot]'` to instead not run the workspace check on dependabot PRs.
> Exclude dependabot from workspace check GH action.

- .github/workflows/release.yml
- go.mod
- plugin/go.mod
Fix the integration tests step in the release workflow by giving the adjusted path for the `go.mod` (tested [in this fork](https://github.com/IfSentient/grafana-app-sdk/actions/runs/10692236317)).
Also retract the release that tried to build with this error (no release binaries), and the previous release (v0.18.3) as that tag is mismatched between GOPROXY and here. [Retraction is the correct way to remove a tag per go](https://go.dev/ref/mod#go-mod-file-retract), so the v0.18.3 tag being deleted and replaced was incorrect behavior and should be listed in the retracted list in `go.mod` in both main and `plugin` modules.
> Fix Integration Tests Workflow and Retract Bad Tags

- cmd/grafana-app-sdk/generate.go
- codegen/jennies/schema.go
- codegen/templates/schema.tmpl
- codegen/templates/templates.go
Give selectable field data awareness of if it's an optional field, and have codegen use pointer logic if so.
Resolves https://github.com/grafana/grafana-app-sdk/issues/407
> [codegen] Fix Codegen for Optional `selectableFields` Values

- cmd/grafana-app-sdk/generate.go
- cmd/grafana-app-sdk/main.go
- cmd/grafana-app-sdk/project.go
This PR adds a prominent warning to users when running the CLI with the `--format=thema` flag that thema support is deprecated and it will be removed in a future release. The warning message points to the docs on writing kinds for how to write a kind in the CUE format instead.
Resolves https://github.com/grafana/grafana-app-sdk/issues/275
> Add warning to CLI output when using --format=thema

- cmd/grafana-app-sdk/project_local.go
- go.work.sum
Continuing efforts to move App O11y onto app sdk: 
App o11y has some boolean values in it's `pluginJson` which was causing error `Error: unable to parse pluginJson key "someKey"`, found that boolean yaml values were not being handled
> Allow bool values in pluginJson

- .github/dependabot.yml
Now that we have an LTS branch which we would like to keep dependencies up-to-date on, add entries in dependabot for targeting that branch as well as `main`.
> Add dependabot entries for the lts/v0.24 branch.

- .github/workflows/lts.yml
- .github/workflows/pr.yml
- go.mod
- go.sum
- go.work.sum
It looks like GH workflows are run based on the source branch of the PR, not from the versions in `main`. Introduce the LTS workflows from `main` (using the wildcard again) to the v0.24 LTS branch.
Also downgrade CUE which was upgraded by dependabot without tests, as tests fail on the newer version of CUE.
> Add LTS workflows, downgrade CUE

- k8s/webhooks.go
- k8s/webhooks_test.go
Have the k8s.WebhookServer use GroupVersionKind when mapping validating and mutating controllers, rather than GroupKind. The methods for adding admission control already use `resource.Kind`, which is a GVK-scoped object, so just support this when storing in the relation map and lookups for handling requests.
> [webhooks] Support Version Distinction in Admission Control

- go.work.sum
- k8s/webhooks.go
- k8s/webhooks_test.go
Apply bugfix changes in https://github.com/grafana/grafana-app-sdk/pull/478 to `lts/v0.24` branch. Original PR contents follow:
Have the k8s.WebhookServer use GroupVersionKind when mapping validating and mutating controllers, rather than GroupKind. The methods for adding admission control already use `resource.Kind`, which is a GVK-scoped object, so just support this when storing in the relation map and lookups for handling requests.
> [LTS v0.24][webhooks] Support Version Distinction in Admission Control

- cmd/grafana-app-sdk/main.go
- cmd/grafana-app-sdk/project_local.go
- cmd/grafana-app-sdk/templates/local/Tiltfile
- go.work.sum
Motivation: I wanted to adopt the grafana-app-sdk tooling and structure for an existing plugin because we have plans to introduce some custom Kinds there. However, in the spirit of smaller changes, I wanted to restructure the project without adding custom Kinds. [You can see my example here](https://github.com/grafana/grafana-pdc-app/pull/541).
This PR shows what I needed to be able to make use of `grafana-app-sdk project local generate` when I didn't have any custom kinds defined.
I couldn't see a nice way to refactor the cue generator to gracefully handle the lack of a cue module (and it didn't feel right), so I added this `none` format which indicates that we don't have any kinds defined. 
Happy to be guided on this, I mainly made this PR as a discussion point. But I'd love to be able …
> allow project local generate to work with no kinds defined

- cmd/grafana-app-sdk/templates/manifest.cue.tmpl
- codegen/cuekind/def.cue
- codegen/jennies/backendplugin.go
- codegen/testing/golden_generated/manifest/go/testkinds/testapp_manifest.go.txt
- codegen/testing/golden_generated/manifest/test-app-manifest.yaml.txt
- docs/tutorials/issue-tracker/01-project-init.md
- docs/tutorials/issue-tracker/02-defining-our-kinds.md
- docs/tutorials/issue-tracker/03-generate-kind-code.md
- docs/tutorials/issue-tracker/04-boilerplate.md
- docs/tutorials/issue-tracker/05-local-deployment.md
- docs/tutorials/issue-tracker/06-frontend.md
- docs/tutorials/issue-tracker/07-operator-watcher.md
- docs/tutorials/issue-tracker/cue/issue-v1.cue
- docs/tutorials/issue-tracker/cue/issue-v2.cue
- docs/tutorials/issue-tracker/cue/issue-v3.cue
- docs/tutorials/issue-tracker/cue/issue-v4.cue
- docs/tutorials/issue-tracker/frontend-files/issue-client.ts
- docs/tutorials/issue-tracker/frontend-files/main.tsx
- operator/opinionatedwatcher.go
- simple/app.go
Update the tutorial doc based on the changes from https://github.com/grafana/grafana-app-sdk/pull/483 and https://github.com/grafana/grafana-app-sdk/pull/491. Running through the tutorial again ran into a few bugs that this PR also resolves:
* The template kind used `permissions` instead of `extraPermissions`
* The default plugin name uses the full group, which contains `.` and is invalid. Fixed to use only the appName portion
* The updated kind in `cue.def` still had a reference to `apiResource` in the version map for inheriting validation/mutation, fixed to not use apiResource
* Prometheus metrics for watchers cannot be exposed in the `simple.App` design as they can for `simple.Operator`, updated `operator.OpinionatedWatcher` to expose metrics from wrapped watchers, and a method to …
> [App Manifest + Docs] Tutorial Doc Update for New Manifest, Associated Fixes

- examples/operator/opinionated/reconciler/main.go
- examples/operator/opinionated/watcher/main.go
- operator/informer_controller.go
- operator/informer_customcache.go
- operator/informer_kubernetes.go
- simple/app.go
- simple/operator.go
Reduce number of New functions in the operator package to a singular New for each type with an options struct. Future new functionality for any type in the operator package can now be added to the options struct for that type, without needing additional New methods, or breaking the signature of an existing New method.
Relates to https://github.com/grafana/grafana-app-sdk/issues/454
> [operator] Clean up New functions

- .github/workflows/dependabot.yml
https://github.com/grafana/grafana-app-sdk/pull/488 is the only dependabot PR open at the moment, and it made me realize i missed the `lts` branch in #554
> [ci] Add lts branch to dependabot action

- .github/workflows/dependabot.yml
* adds `id-token: write` permission, which is needed to prevent [this error](https://github.com/grafana/grafana-app-sdk/actions/runs/12599467998/job/35116430246#step:2:49)
* switch back to github action bot in git commits (this fix is already applied on the LTS branch)
* prevent forks from triggering go workspace action
> [ci] Update go workspace action permissions

- .github/workflows/dependabot.yml
Follow up to https://github.com/grafana/grafana-app-sdk/pull/561 for `lts/v0.24`
> [ci] Prevent forks from running go workspace update action

- codegen/cuekind/generators.go
- codegen/cuekind/generators_test.go
- codegen/jennies/constants.go
- codegen/templates/constants.tmpl
- codegen/templates/templates.go
- codegen/testing/golden_generated/go/groupbygroup/customapp/v0_0/constants.go.txt
- codegen/testing/golden_generated/go/groupbygroup/customapp/v1_0/constants.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v1/constants.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v2/constants.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v0_0/constants.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v1_0/constants.go.txt
Generate exported `Group`, `Version`, and `GroupVersion` constants for each generated kind's package (when grouping kinds by version, only one set of constants will be generated for the package). This allows for a more convenient way to reference these constants vs. using the Kind accessor method, and then getting its Group/Version, especially when kinds are grouped by version, so multiple kinds are in the same package, sharing the same constants.
This is implemented as a new generated file because it has to be generated only once per package, unlike the other kind files which exist once per kind.
Resolves https://github.com/grafana/grafana-app-sdk/issues/515
> [codegen] Generate exported constants for group and version.

- operator/reconciler.go
- operator/reconciler_test.go
Related to https://github.com/grafana/grafana-app-sdk/issues/559, added debug logging and tracing similar to what `OpinionatedWatcher` already has. While testing, changed the logic in the `OpinionatedReconciler` to resolve two issues:
1. Previously, when an update added the `deletionTimestamp`, the `OpinionatedReconciler` would remove the finalizer and return, and then rely on the subsequent delete event to be propagated down to the downstream reconciler for delete behavior. This introduces an edge case that is addressed in `OpinionatedWatcher` but missed here, where, if the downstream's processing of the delete fails, the object is still deleted in the API server, possibly leaving a bad state (in `OpinionatedWatcher`, the finalizer is not removed until the downstream delete is …
> [OpinionatedReconciler] Add debug logging and tracing, change some logic to avoid retry loops on deletes

- app/runner.go
- k8s/client.go
- k8s/client_test.go
- k8s/gvclient.go
- k8s/schemaless.go
- k8s/schemaless_test.go
- resource/client.go
- resource/simplestore.go
- resource/simplestore_test.go
- resource/store.go
- resource/store_test.go
- resource/typedstore.go
- resource/typedstore_test.go
Added `DeleteOptions` to `resource.Client.Delete` and `resource.SchemalessClient.Delete`, along with implementation in `k8s.Client` and `k8s.SchemalessClient`.
`resource.DeleteOptions` includes `preconditions` and `propagationPolicy` from [kubernetes' delete options](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/delete-options/).
Resolves https://github.com/grafana/grafana-app-sdk/issues/456
> [Client] Add options to Client.Delete and SchemalessClient.Delete

- cmd/grafana-app-sdk/generate.go
This commit fixes codegen issue that omits generating Go manifest file if the codegen is invoked with `defencoding=none`.
The `defencoding=none` is supposed to only omit generating the CRD definitions for kinds & manifest but still generate the Go file for the manifest correctly.
> Fix codegen omitting Go manifest file with `defencoding=none`

- resource/typedstore.go
- resource/typedstore_test.go
Make the behavior of `TypedStore.Update` match the described behavior in the godoc with respect to ResourceVersion. If the ResourceVersion is empty, return an error, and otherwise always pass the ResourceVersion to the underlying UpdateOptions.
> Make the behavior of `TypedStore.Update` match the described behavior in the godoc

- resource/wrappedobject.go
Added `resource.WrappedObject` for creating a `resource.Object`-implmenting type from a kubernetes type which doesn't use 'spec' in its schema (for example: ClusterRole). Also added `resource.PassthroughJSONCodec` for said type which does no additional logic aside from JSON Marshal/Unmarshal (unlike `resource.JSONCodec` which uses the accessors in `resource.Object` to structure the resulting JSON).
> Added resource.WrappedObject for creating a resource.Object-implmenting type from a non-spec-based type

- operator/informer_controller.go
- simple/app.go
Call `ErrorHandler` on reconciler errors, and ensure that a custom `ErrorHandler` is properly set in `simple.NewApp`
> [operator] Call ErrorHandler on reconciler errors

- cmd/grafana-app-sdk/project.go
- docs/tutorials/issue-tracker/04-boilerplate.md
- docs/tutorials/issue-tracker/06-frontend.md
This PR updates the Issue Tracker tutorial with few small fixes.
Apart from these fixes, I had to change `issue-tracker-project-app` part of URL (eg. in `curl http://grafana.k3d.localhost:9999/api/plugins/issue-tracker-project-app/resources/v1/issues` command) to `issuetrackerprojectapp`. I'm not sure why, or whether this is specific to my installation somehow, or version, so I didn't update the commands in this PR.
> Small fixes for the Issue Tracker tutorial

- docs/tutorials/issue-tracker/05-local-deployment.md
- docs/tutorials/issue-tracker/06-frontend.md
- docs/tutorials/issue-tracker/08-adding-admission-control.md
Update Tutorial plugin links from `issue-tracker-project-app` to `issuetrackerproject-app`, as the generated plugin name changed with app manifest work. Some of these were updated when that happened, but a few were missed.
Follow-up to https://github.com/grafana/grafana-app-sdk/pull/619
CC @pstibrany
> [docs] Update Tutorial plugin links

- app/appmanifest/v1alpha1/appmanifest_spec_gen.go
- app/appmanifest/v1alpha1/conversion.go
- app/appmanifest/v1alpha1/conversion_test.go
- app/appmanifest/v1alpha1/generated_code_test.go
- app/appmanifest/v1alpha1/testfiles/manifest-01.json
- app/appmanifest/v1alpha1/testfiles/schema-01.json
- app/appmanifest/v1alpha1/testfiles/spec-01.json
- app/definitions/app-manifest-manifest.json
- app/definitions/appmanifest.apps.grafana.com.json
- app/manifest.cue
This is a follow-up to https://github.com/grafana/grafana-app-sdk/pull/639
Add tests for generated AppManifest code and conversion code. As part of this, I realized that some fields (`extraPermissions` and `selectableFields`) should be optional in the CUE, so as not to be required in the CRD, so I updated those fields and re-ran `make generate`.
> [AppManifest] Add tests for generated AppManifest code and conversion code

- .golangci.yml
- operator/reconciler.go
- operator/runner.go
Disable revive:use-errors-new linter, as it requires too many changes to the codebase for now.
Also ignore two other linter errors that have cropped up.
> Disable revive:use-errors-new linter

- codegen/templates/plugin/main.tmpl
Don't use `prometheus.MustRegister` in generated plugin code's `newInstanceFactory `to avoid panicking if and when it is called again during the plugin lifetime.
In order to still denote an error if a non-already-registered error occurs, check if the error is not an instance of `prometheus.AlreadyRegisteredError`, and return an error from the factory method if so.
> [codegen] Don't use `prometheus.MustRegister` in generated plugin code's `newInstanceFactory`

- cmd/grafana-app-sdk/templates/Makefile.tmpl
- cmd/grafana-app-sdk/templates/operator_Dockerfile.tmpl
- codegen/templates/resourceobject.tmpl
- codegen/testing/golden_generated/go/groupbygroup/customapp/v0_0/customkind_object_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/customapp/v1_0/customkind_object_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v1/testkind2_object_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v1/testkind_object_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v2/testkind_object_gen.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v0_0/customkind_object_gen.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v1_0/customkind_object_gen.go.txt
- resource/object.go
- resource/object_test.go
Fix CopyObject to deep copy the object rather than shallow copy, introduce CopyObjectInto to do a full deep copy using reflection. Add tests for CopyObject and CopyObjectInto. Add DeepCopy and DeepCopyInto methods to generated object and spec/subresource code.
> Fix CopyObject to deep copy the object rather than shallow copy

- codegen/jennies/typescript.go
Pass correct package name (same as in Go) to cog when generating TypeScript code.
Without proper package name schema traversal doesn't work properly and some edge cases of valid CUE end up producing broken TS code.
> Use correct package name for TypeScript codegen

- cmd/grafana-app-sdk/templates/operator_Dockerfile.tmpl
- codegen/jennies/operator.go
- codegen/templates/app/watcher.tmpl
- codegen/templates/constants.tmpl
- codegen/templates/templates.go
- codegen/testing/golden_generated/go/groupbygroup/customapp/v0_0/constants.go.txt
- codegen/testing/golden_generated/go/groupbygroup/customapp/v1_0/constants.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v1/constants.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v2/constants.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v0_0/constants.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v1_0/constants.go.txt
Rename generated 'Group' and 'Version' constants to 'APIGroup' and 'APIVersion' to avoid naming conflicts with kinds. Use machinename+version for package alias in generated watcher code to avoid similar conflicts.
Resolves https://github.com/grafana/grafana-app-sdk/issues/666
> [codegen] Rename generated 'Group' and 'Version' constants

- CODEOWNERS
Update CODEOWNERS to be consistent with `main`.
To make sure we have correct code owners for PRs to the v0.24 LTS branch.
> Make sure CODEOWNERS are consistent with main

- health/observer.go
- resource/object.go
- resource/object_test.go
`resource.CopyObject` and `resource.CopyObjectInto` incorrectly zero `time.Time` values when doing their copy, as it tries to copy `time.Time` instances as structs using reflection. Since `time.Time` has no exported fields, this does not work. To fix this behavior, check if the struct to be copied is `typeOf(time.Time)`, and, if so, directly copy it with `dst.Set(src)`, rather than recursively calling `CopyObjectInto` to copy it as a user-defined struct.
This does bring up the issue that any other "special" types which have custom `MarshalJSON`/`UnmarshalJSON` implementations but no exported fields will also fail with the deep copy performed by `resource.CopyObject`/`resource.CopyObjectInto`. I'm not sure if this is a restriction we want to live with, or attempt to solve here.
Ultimately, …
> Fix resource.CopyObject and resource.CopyObjectInto zeroing time.Time

- resource/object.go
- resource/object_test.go
Previous PR to fix `resource.CopyObject` and `resource.CopyObjectInto` for `time.Time` elements (https://github.com/grafana/grafana-app-sdk/pull/744) had a small bug with `*time.Time` types, and the addition to the test only tested `time.Time`. Added a `*time.Time` element to the test, and fixed the bug where it improperly checked if the pointer is of type `time.Time`, rather than the dereferenced pointer.
> Fix resource.CopyObject for *time.Time elements.

- .github/workflows/dependabot.yml
- .github/workflows/lts.yml
- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
Update workflows to pass zizmor checks:
* Add explicit permissions block for all workflows
* use commit hashes for runners instead of version tags (hashes are the commits associated with the tags at time of writing)
* set `persist-credentials` to `false` for all checkout actions
* Set `cache: false` for goreleaser to avoid cache poisoning
> [Workflows] Update workflows to pass zizmor checks.

- k8s/gvclient.go
- resource/client.go
Add a `Subresource` field to `PatchOptions` similar in behavior to the `Subresource` field in `UpdateOptions`, to allow a `Patch` request to patch a subresource.
Noted in godoc that for an empty subresource, the entire subresource must be set in the patch request. Otherwise, kubernetes responds with a 422 status and a message of "the server rejected our request due to an error in our request" (with no other details).
> Allow Subresource Patching in PatchOptions and k8s.Client

- .github/zizmor.yml
For PR's that are sourced from a fork, the zizmor check will fail without a config present in the fork's `.github` directory. There is work being done to fix this upstream in the reusable workflow itself, but for now, we need the file in the local repo so it will be present in the fork.
> Add local zizmor config

- k8s/apiserver/installer.go
Fix the ParameterCodec used by InstallAPIs to use the installer scheme rather than the metav1 scheme's ParameterCodec.
This was resulting in a bug in certain situations with `CallResource` where an error would be returned that the kind couldn't be found in the scheme, this was due to the decoding using the ParameterCodec from the `metav1` package, which is based on the unexported metav1 scheme.
> [k8s.apiserver] Fix the ParameterCodec used by InstallAPIs 

- cmd/grafana-app-sdk/project_local.go
- cmd/grafana-app-sdk/templates/local/config.yaml
- cmd/grafana-app-sdk/templates/local/generated/k3d-config.json
Allow specifying additional volume locations to mount in the k3d deployment in `./local/config.yaml`, which get turned into 'volumes' entries in the generated `./local/generated/k3d-config.json`. Allows resolving of local paths into absolute ones (as absolute paths are required by k3d).
> [Local Env] Allow specifying additional volume locations in `./local/config.yaml`

- k8s/apiserver/strategy.go
Fix `GenerateName` to use `names.SimpleNameGenerator`, rather than just returning the base with a hyphen appended.
> [apiserver] Fix `GenerateName`

- k8s/gvclient.go
To make debugging issues that stem from kubernetes interactions (especially from the `cache.Reflector`), log request methods and URL at the debug level for all requests using the k8s client(s).
> [k8s] Add debug logging for all requests using the kubernetes client

- k8s/dynamic.go
- operator/opinionatedwatcher.go
- operator/opinionatedwatcher_test.go
- operator/reconciler.go
- operator/reconciler_test.go
- simple/app.go
The patch operation being done currently by the `operator.OpinionatedWatcher` and `operator.OpinionatedReconciler` overwrites the finalizers in the list on Add, rather than appending if there are existing finalizers. As the logic to correctly patch the finalizers, especially with multiple operators watching the same kinds, is a little more complex than a single patch request, this PR introduces the `FinalizerUpdater` interface and an unexported implementation that is used by both `operator.OpinionatedWatcher` and `operator.OpinionatedReconciler`. 
The `FinalizerUpdater` implementation now handles using resourceVersion to avoid out-of-date RV issues, and will append to or create the finalizer list as appropriate on `AddFinalizer`. It also handles a few retries with a simple backoff and …
> [OpinionatedWatcher/OpinionatedReconciler] Fix overwriting of finalizers with concurrent apps watching the same kinds

- k8s/dynamic.go
This PR is a backport of https://github.com/grafana/grafana-app-sdk/pull/900 onto `lts/v0.24`.
The kubernetes `dynamic.DynamicClient`'s `ServerPreferredResources` method [can return an error alongside results](https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L493) to indicate that some apigroup discoveries failed, but others succeeded. To handle this, if we have any results, just log the error to the default logger, and still process the results. If there are no results, return the error.
> [k8s] Allow partial discovery failure for the dynamic patcher

- app/appmanifest/v1alpha1/conversion.go
- app/appmanifest/v1alpha2/conversion.go
- operator/errors.go
- operator/finalizers.go
- operator/informer_controller_test.go
- operator/opinionatedwatcher.go
- operator/opinionatedwatcher_test.go
- operator/reconciler.go
- operator/reconciler_test.go
This PR adds a new error type (`FinalizerError` interface, `FinalizerOperationError` implementation used by `finalizerUpdater`) which includes the patch request details. This error is now checked in all OpinionatedWatcher/OpinionatedReconciler finalizer operations to log the patch request details if an error is returned.
This error can also now be checked with `errors.As` in upstream error handlers as well for additional improved logging/error handling.
> [operator] Improve Finalizer Errors

- operator/metrics_server.go
- operator/runner.go
This commit adds pprof endpoints to the metrics server and a flag to enable them to the metrics config.
This allows operators to support conprof out-of-the-box, similarly to how metrics and traces are supported.
> Add pprof endpoints to the metrics server

- codegen/templates/resourceclient.tmpl
- codegen/testing/golden_generated/go/groupbygroup/customapp/v0_0/customkind_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/customapp/v1_0/customkind_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v1/testkind2_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v1/testkind_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v2/testkind_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbygroup/testapp/v3/testkind_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v0_0/customkind_client_gen.go.txt
- codegen/testing/golden_generated/go/groupbykind/customkind/v1_0/customkind_client_gen.go.txt
- examples/apiserver/apis/example/v1alpha1/testkind_client_gen.go
Include `resource.Identifier` in generated kind clients' subresource update methods
> [codegen] Fix Generated Kind Client Subresource Update

- docs/watching-unowned-resources.md
- simple/app.go
Default AppUnmanagedKinds to not using the opinionated reconcilers/watchers, and add a section to the watching unmanaged kinds doc on this behavior.
`AppUnmanagedKind.ReconcileOptions` has been changed from `BasicReconcileOptions` to `UnmanagedKindReconcileOptions`, which inverts the `UsePlain` boolean to `UseOpinionated` (so the default is now to _not_ use the opinionated variant).
> [simple.App] Default AppUnmanagedKinds to not using the opinionated reconcilers/watchers

- codegen/templates/app/app.tmpl
- operator/informer_concurrent.go
- operator/informer_customcache.go
- operator/informer_customcache_test.go
- operator/informer_kubernetes.go
- operator/informer_kubernetes_test.go
- simple/app.go
- simple/app_test.go
- simple/operator.go
- **Added `EventTimeout` option** to `CustomCacheInformerOptions` and `KubernetesBasedInformerOptions`
- **Updated `ListerWatcher`** to use contextual `ListWithContextFunc` and `WatchFuncWithContext`
- **Modified `NewCustomCacheInformer` signature** to pass options via `CustomCacheInformerOptions` struct
- **EventTimeout prevents resource leaks** by dropping events that take too long to process
- **Contextual ListerWatcher improves cancellation handling** and resource cleanup during watch operations
- **Configurable options provide better control** over informer behavior without breaking existing functionality
⚠️ **Breaking Change**: `NewCustomCacheInformer` now requires a `CustomCacheInformerOptions` parameter:
```golang
// Before
inf := NewCustomCacheInformer(store, lw, kind)
// After …
```
> Add EventTimeout option and use contextual `cache.ListWatch` methods

- resource/kind.go
- resource/kind_test.go
There are a few places jumping some hoops to get the GVR from a manifest:
https://github.com/grafana/grafana/blob/v12.2.0/pkg/api/short_url.go#L119
Ideally:
```
gvr := schema.GroupVersionResource{
Group:    v1alpha1.ShortURLKind().Group(),
Version:  v1alpha1.ShortURLKind().Version(),
Resource: v1alpha1.ShortURLKind().Plural(),
}
return &shortURLK8sHandler{
gvr:   ...
```
with this change, we could use:
```
return &shortURLK8sHandler{
gvr:   v1alpha1.ShortURLKind().GroupVersionResource()
```
Most references to [.Plural()](https://github.com/search?q=repo%3Agrafana%2Fgrafana%20Plural()&type=code) really wants the GVR
> Kind: Support GVK+GVR without pointer reciever
