grafana/grafana-app-sdk

.gitignore, README.md
Added missing .gitignore, fixed a couple of broken links in the README.
=> Added .gitignore

codegen/generator_typescript.go, codegen/testing/golden_generated/customkind_types.gen.ts.txt
Export TS types in cuetsy config for the TS Jenny.
=> Export TS types in cuetsy config for the TS Jenny.

operator/opinionatedwatcher.go
Compare generation in OpinionatedWatcher.Update before we check for the presense of the finalizer. This allows the underlying watcher to update a subresource without the OpinionatedWatcher attempting to call AddFunc again on that change.
=> [operator] Check for generation change before presense of finalizer

plugin/kubeconfig/loader.go, plugin/kubeconfig/loader_test.go
Support base64-encoded kubeconfig values in secureJsonData. The loader will attempt to parse kubeconfig / namespace keys as base64-encoded values (using standard encoding) and fall back to treating them as normal strings upon error.
Automatic provisioning code writes data to settings in base64-encoded format.
=> Support base64-encoded kubeconfig values in secureJsonData

operator/informer_controller_test.go
Improve InformerController RetryDequeuePolicy tests to not rely on timing of concurrent events. It makes the tests slightly more complicated to understand, so I also added more comments on what is happening.
Resolves https://github.com/grafana/grafana-app-sdk/issues/42
=> Improve Tests added for RetryDequeuePolicy

docs/README.md, docs/admission-control.md
Added a doc page for admission control.
=> [docs] Admission Control/Webhooks

docs/custom-kinds.md, docs/tutorials/issue-tracker/02-defining-our-kinds.md, docs/tutorials/issue-tracker/03-generate-kind-code.md, docs/tutorials/issue-tracker/04-boilerplate.md, docs/tutorials/issue-tracker/cue/issue-v1.cue, docs/tutorials/issue-tracker/cue/issue-v2.cue
Updated custom kinds doc and tutorial to use the new cue kind instead of thema.
=> [docs] Update Docs for CUE Kind

docs/README.md
Thema is not mentioned in the document linked by README.md, just tidying up.
=> chore: Update docs/README.md to remove Thema reference.

codegen/jennies/codec.go, codegen/jennies/crd.go, codegen/jennies/resourceobject.go, codegen/jennies/schema.go, codegen/jennies/typescript.go, codegen/templates/resourceobject.tmpl, codegen/templates/templates.go, codegen/templates/themacodec.tmpl, codegen/testing/golden_generated/customkind/customkind_object_gen.go.txt, codegen/testing/golden_generated/customkind/customkind_thema_codec_gen.go.txt, codegen/thema/jennies/codec.go, k8s/client_registry.go, k8s/gvclient.go, k8s/negotiator.go, k8s/translation.go, resource/kind.go, resource/object.go, resource/simplestore.go, resource/typedobject.go, resource/typedstore.go, resource/untypedobject.go
Final miscellaneous fixes for linter, and a few bugs discovered when doing more thorough testing in local kubernetes (main one was the annotation prefix not being used in generated code).
After this PR, I will be creating a PR to merge the `kind-object-refactor` branch into `main`.
=> [Kind/Object Refactor] Misc Final Fixes

docs/tutorials/issue-tracker/04-boilerplate.md, docs/tutorials/issue-tracker/06-frontend.md, docs/tutorials/issue-tracker/07-operator-watcher.md
Update tutorial with more front-end details, some small corrections to change issue.Object to issue.Issue where appropriate.
=> [docs] Update Tutorial with Details on Front-End Code

docs/resource-stores.md, resource/typedstore.go
Improve the Resource Stores doc with updates and examples, and include a note on the deprecation of `SimpleStore`, informing users to open an issue or discussion if there is a use-case for SimpleStore that TypedStore does not cover.
Resolves https://github.com/grafana/grafana-app-sdk/issues/254
=> [docs] Improve Resource Stores Doc

cmd/grafana-app-sdk/templates/Makefile.tmpl
Fix the plugin dist copy into local/mounted-files/plugin/dist
=> [CLI] Fix `local/deploy_plugin` target in Makefile

cmd/grafana-app-sdk/generate.go
Allow for a 'none' option for --crdencoding to turn off CRD generation.
=> [CLI] Allow Disabling CRD Generation

.golangci.yml, codegen/generator.go, codegen/jennies/crd.go, codegen/jennies/gotypes.go, k8s/gvclient.go, k8s/webhooks.go, operator/cache_memcached.go, operator/informer_controller.go, operator/informer_kubernetes.go, operator/util.go, plugin/router/resourcegroup_router.go, plugin/router/router.go
A previous update of golangci-lint made new linter issues appear, fix those issues (or ignore when needed).
=> Update linter config and fix/ignore linter issues where appropriate.

.github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, codegen/templates/operator/main.tmpl
Future TODO: explore using a [composite action](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action) or [reusable workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) for this instead of duplication.
=> Add copy of integration-test step to PR and main workflows.

.github/workflows/lts.yml, .github/workflows/pr.yml
PR tests aren't currently run for the LTS branch, fix that.
=> Add LTS branch build workflow and have tests run on PR's to LTS branch

operator/informer_controller_test.go
Refactor a few of the InformerController tests to rely less on timing and expecting events to happen a number of times within an interval, which can lead to failures on under-resourced machines (such as github actions). Particular focus on reworking `TestInformerController_Run_BackoffRetry`, which frequently fails GH actions runs and needs to be retried.
Resolves https://github.com/grafana/grafana-app-sdk/issues/420
=> [tests] Improve InformerController tests to rely less on timing

.github/workflows/test.yml, Makefile, go.mod, go.sum, go.work, logging/go.mod, logging/go.sum
This makes logging a proper submodule, such that depending on the entirety of the SDK is not necessary just to get to work with logging.
Split off from #574.
=> [logging] Make a proper submodule

resource/typedstore.go, resource/typedstore_test.go
Make the behavior of `TypedStore.Update` match the described behavior in the godoc with respect to ResourceVersion. If the ResourceVersion is empty, return an error, and otherwise always pass the ResourceVersion to the underlying UpdateOptions.
Duplicate of https://github.com/grafana/grafana-app-sdk/pull/595 applied to the LTS branch.
=> Make the behavior of `TypedStore.Update` match the described behavior in the godoc

k8s/dynamic.go
Currently `k8s.DynamicPatcher` ignores `Subresource` and `DryRun` fields in the `PatchOptions`, this PR implements both options in the underlying patch request(s).
=> [k8s] Add subresource and DryRun support to k8s.DynamicPatcher

simple/app.go
Wrap the DefaultInformerSupplier in a 10-max-workers conrrent informer if no InformerSupplier is provided.
Leave the logic of using a custom InformerSupplier untouched.
=> [simple.App] Default to ConcurrentInformer
